# Generated by Django 4.0 on 2022-10-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('project', '0002_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batch_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.batch'),
        ),
    ]
