# Generated by Django 4.0 on 2022-10-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(blank=True, null=True, unique=True)),
                ('DateOfAdmission', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50)),
                ('roll_number', models.IntegerField()),
                ('projet_status', models.CharField(choices=[('Started', 'Started'), ('Not Started', 'Not Started')], default='Started', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('TransGender', 'TransGender')], default='Male', max_length=50)),
                ('dues', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.batch')),
            ],
        ),
    ]
